# LIMP Configuration File

bot:
  name: "${LIMP_SYSTEM_NAME|LIMP}"
  url: "${LIMP_SYSTEM_URL}"
  debug: "${LIMP_SYSTEM_DEBUG|false}"
  system_prompts:
    - "${LIMP_SYSTEM_PROMPT|You are a helpful AI assistant that can help users interact with external systems.}"
    - Today's date (YYYY-MM-DD) is ${today}.
    - "${LIMP_SYSTEM_PROMPT_2|Always be polite and professional in your responses.}"
    - "${LIMP_SYSTEM_PROMPT_3|If you need to access external systems, ask the user to authorize access first.}"
    - "${LIMP_SYSTEM_PROMPT_4}"
    - "${LIMP_SYSTEM_PROMPT_5}"
    - "${LIMP_SYSTEM_PROMPT_6}"
    - "${LIMP_SYSTEM_PROMPT_7}"
    - "${LIMP_SYSTEM_PROMPT_8}"
    - "${LIMP_SYSTEM_PROMPT_9}"

database:
  url: "${DATABASE_URL|sqlite:///./limp.db}"
  echo: false

llm:
  provider: "openai"
  api_key: "${OPENAI_API_KEY}"
  model: "${OPENAI_MODEL|gpt-5-mini}"
  max_tokens: "${OPENAI_MAX_TOKENS|4096}"
  temperature: 0.7
  max_iterations: ${LIMP_SYSTEM_MAX_ITERATIONS|12}
  # Context management settings
  context_threshold: ${LIMP_SYSTEM_CONTEXT_THRESHOLD|0.75}
  context_window_size: ${LIMP_SYSTEM_CONTEXT_WINDOW_SIZE}
  summary_max_tokens: ${LIMP_SYSTEM_SUMMARY_MAX_TOKENS|4096}

external_systems:
  - name: "${EXTERNAL_SYSTEM_NAME|example-system}"
    primary: true
    oauth2:
      client_id: "${EXTERNAL_SYSTEM_OAUTH2_CLIENT_ID}"
      client_secret: "${EXTERNAL_SYSTEM_OAUTH2_CLIENT_SECRET}"
      authorization_url: "${EXTERNAL_SYSTEM_OAUTH2_AUTHORIZATION_URL}"
      token_url: "${EXTERNAL_SYSTEM_OAUTH2_TOKEN_URL}"
      scope: "${EXTERNAL_SYSTEM_OAUTH2_SCOPE|read write}"
      test_endpoint: "${EXTERNAL_SYSTEM_OAUTH2_TEST_ENDPOINT}"
    openapi_spec: "${EXTERNAL_SYSTEM_OPENAPI_SPEC}"
    base_url: "${EXTERNAL_SYSTEM_BASE_URL}"

im_platforms:
  - platform: "slack"
    app_id: "${SLACK_APP_ID}"
    client_id: "${SLACK_CLIENT_ID}"
    client_secret: "${SLACK_CLIENT_SECRET}"
    signing_secret: "${SLACK_SIGNING_SECRET}"
  
admin:
  enabled: "${ADMIN_ENABLED|false}"
  username: "${ADMIN_USERNAME}"
  password: "${ADMIN_PASSWORD}"

logging:
  level: "${LIMP_SYSTEM_LOGGING_LEVEL|INFO}"
