"""add_channel_id_and_thread_id_to_conversations

Revision ID: 4844f8b1a3f8
Revises: bf6c8dd7e997
Create Date: 2025-10-25 20:18:18.850757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4844f8b1a3f8'
down_revision: Union[str, None] = 'bf6c8dd7e997'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('channel_id', sa.String(), nullable=True))
    op.add_column('conversations', sa.Column('thread_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'thread_id')
    op.drop_column('conversations', 'channel_id')
    # ### end Alembic commands ###
