"""Add external_id field to messages table

Revision ID: bf6c8dd7e997
Revises: e4865455c164
Create Date: 2025-10-05 17:03:36.210069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf6c8dd7e997'
down_revision: Union[str, None] = 'e4865455c164'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('external_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_messages_external_id'), 'messages', ['external_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_external_id'), table_name='messages')
    op.drop_column('messages', 'external_id')
    # ### end Alembic commands ###
