"""Add slack_organizations table

Revision ID: e4865455c164
Revises: 523ec2179fd5
Create Date: 2025-10-02 19:11:36.100403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4865455c164'
down_revision: Union[str, None] = '523ec2179fd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('slack_organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('token_type', sa.String(), nullable=False),
    sa.Column('scope', sa.Text(), nullable=True),
    sa.Column('bot_user_id', sa.String(), nullable=True),
    sa.Column('app_id', sa.String(), nullable=True),
    sa.Column('team_id', sa.String(), nullable=True),
    sa.Column('team_name', sa.String(), nullable=True),
    sa.Column('enterprise_id', sa.String(), nullable=True),
    sa.Column('enterprise_name', sa.String(), nullable=True),
    sa.Column('authed_user_id', sa.String(), nullable=True),
    sa.Column('authed_user_access_token', sa.Text(), nullable=True),
    sa.Column('authed_user_token_type', sa.String(), nullable=True),
    sa.Column('authed_user_scope', sa.Text(), nullable=True),
    sa.Column('installed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_slack_organizations_id'), 'slack_organizations', ['id'], unique=False)
    op.create_index(op.f('ix_slack_organizations_organization_id'), 'slack_organizations', ['organization_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_slack_organizations_organization_id'), table_name='slack_organizations')
    op.drop_index(op.f('ix_slack_organizations_id'), table_name='slack_organizations')
    op.drop_table('slack_organizations')
    # ### end Alembic commands ###
